### ISSUE TITLE
bug: doesn't actually work

### ISSUE THREAD

**Issue by niftylettuce** [egoist/promise.series#2]
this package doesn't work, but <https://github.com/der-On/es6-promise-series> does (albeit their package name in their README is wrong, it works)

**Comment by egoist** [comment]
what do you mean by *not work*

**Comment by niftylettuce** [comment]
I tried a simple test but it didn't execute the promises.

```
const promiseSeries = require('promise.series');
const promises = [ Promise.resolve(), Promise.resolve() ];
promiseSeries(promises).then(console.log).catch(console.error);
```

**Comment by egoist** [comment]
see https://github.com/egoist/promise.series/blob/master/README.md#tasks

**Comment by egoist** [comment]
If you pass `[ Promise.resolve(), Promise.resolve() ]` they will not be executed in series but in parallel, so you pass `[ () => Promise.resolve(), () => Promise.resolve() ]` instead.
